name: "Label PRs"

on:
  # only execute base branch actions
  pull_request_target:

jobs:
  labels:
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'freifunk-gluon'
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: true
